# Jekyll configuration
# https://jekyllrb.com/docs/configuration/

name: Zhitom
description: Welcome to ZhitomÔºÅ

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/zhitom/zhitom.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language en/cn
lan: "cn" 

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
port: 8090

